### ISSUE TITLE
Feature Request: Status Bar

### ISSUE THREAD

**Issue by UInt2048** [hakiett/FastForwardTime#4]
Can you please add status bar support for when unlocked? The lock screen/Notification Center support is great!

**Comment by turtlemaster19** [comment]
P.S. I believe that if the useless Location Services icon is removed, it can be done on iPhone X-like devices, too.

**Comment by turtlemaster19** [comment]
P.P.S. I really like the auto-updating of the seconds every second!

**Comment by hakiett** [comment]
I don't develop anymore sorry.

>

**Comment by UInt2048** [comment]
I am closing due to the improbability of it ever being added.
